// Generated by scripts/ikorodu-axis.mjs from OpenStreetMap data (© OpenStreetMap contributors, ODbL). Do not edit by hand.
// General Hospital Ikorodu gate to the garage roundabout centre: OSM ways 538323260 (Beach Road), 1460813931,
// 778859468 and 1460813930 (Ayangburen Road) and 134580953 (roundabout), scaled by 0.3.
// Game metres: x east, z south, listed from the hospital to the roundabout. The start line is the world origin.

export const IKORODU_AXIS: [number, number][] = [
  [-43.56, 72.98],
  [-33.4, 56.2],
  [-23.24, 39.41],
  [-13.08, 22.62],
  [-3.2, 5.68],
  [6.43, -11.42],
  [16.06, -28.51],
  [25.7, -45.61],
  [34.18, -63.29],
  [42.33, -81.14],
  [49.35, -99.44],
  [55.74, -117.99],
  [62.14, -136.54],
  [68.53, -155.09],
  [73.77, -173.99],
  [78.8, -192.96],
  [84.79, -211.64],
  [90.8, -230.32],
  [96.45, -249.1],
  [100.2, -268.36],
  [103.95, -287.62],
  [105.84, -307.12],
];

/** Metres along the axis from the hospital end to the start line. */
export const IKORODU_START = 85;
