// Generated by scripts/ikorodu-axis.mjs from OpenStreetMap data (© OpenStreetMap contributors, ODbL). Do not edit by hand.
// General Hospital Ikorodu gate to the garage roundabout centre: OSM ways 538323260 (Beach Road), 1460813931,
// 778859468 and 1460813930 (Ayangburen Road) and 134580953 (roundabout), scaled by 0.3.
// Game metres: x east, z south, listed from the hospital to the roundabout. The start line is the world origin.

export const IKORODU_AXIS: [number, number][] = [
  [-36.2, 59.91],
  [-26.04, 43.13],
  [-15.88, 26.34],
  [-5.72, 9.55],
  [4.16, -7.39],
  [13.8, -24.49],
  [23.43, -41.58],
  [33.06, -58.68],
  [41.54, -76.36],
  [49.69, -94.21],
  [56.71, -112.51],
  [63.11, -131.06],
  [69.5, -149.61],
  [75.89, -168.16],
  [81.13, -187.06],
  [86.16, -206.02],
  [92.16, -224.71],
  [98.16, -243.39],
  [103.81, -262.17],
  [107.56, -281.43],
  [111.31, -300.69],
  [113.2, -320.19],
];

/** Metres along the axis from the hospital end to the start line. */
export const IKORODU_START = 70;
