// Generated by scripts/osm-track.mjs from OpenStreetMap data (© OpenStreetMap contributors, ODbL). Do not edit by hand.
// Ojuelegba Road, westbound carriageway, from 112 m east of the Tejuosho market start to under the
// Western Avenue bridge, scaled by 0.38. Game metres: x east, z south, listed east to west.

export const OJUELEGBA_AXIS: [number, number][] = [
  [39.33, -17.14],
  [21.2, -9.23],
  [2.46, -2.97],
  [-16.93, 0.96],
  [-36.33, 3.95],
  [-55.61, 8.38],
  [-74.75, 4.6],
  [-90.98, -6.68],
  [-107.05, -18.21],
  [-123.5, -29.16],
  [-141.16, -38.05],
  [-159.43, -45.62],
  [-178.48, -50.35],
  [-198.24, -50.03],
  [-217.97, -48.86],
  [-237.68, -49.34],
  [-257.02, -53.47],
  [-276.47, -57.03],
  [-295.84, -61.04],
];

/** Metres along the axis from its east end to the start line. */
export const OJUELEGBA_START = 42.56;
