// Generate src/config/ikoroduAxis.ts: the centre line of the road from General Hospital Ikorodu to the garage
// roundabout, scaled down for the game. No network: the points below are the result of routing over the
// OpenStreetMap ways listed in the header (the Out and Back carriageways averaged on the dual carriageway).
// Re-run with:  node scripts/ikorodu-axis.mjs     Road data © OpenStreetMap contributors (ODbL).
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'src', 'config', 'ikoroduAxis.ts');

// Real metres, origin at the junction pin (6.620652, 3.503497), x east, z south. Starts at the hospital gate
// (the 34 m service road inside the gate is left out; the hospital U-turn is built there) and ends at the
// roundabout centre.
const REAL = [[-503, 1289], [-385, 1094], [-265, 881], [-207, 754], [-126, 519], [-95, 402], [-50, 262], [-37, 219], [-8, 70], [-5, 22]];
const SCALE = 0.3;
const STEP = 20; // game metres between axis vertices
const START = 85; // game metres along the axis to the start line

const pts = REAL.map(([x, z]) => [x * SCALE, z * SCALE]);
const cum = [0];
for (let i = 1; i < pts.length; i++) cum.push(cum[i - 1] + Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]));
const total = cum[cum.length - 1];
const at = d => {
  for (let i = 1; i < pts.length; i++) if (d <= cum[i]) { const t = (d - cum[i - 1]) / (cum[i] - cum[i - 1]); return [pts[i - 1][0] + (pts[i][0] - pts[i - 1][0]) * t, pts[i - 1][1] + (pts[i][1] - pts[i - 1][1]) * t]; }
  return pts[pts.length - 1];
};
const n = Math.round(total / STEP);
const raw = Array.from({ length: n + 1 }, (_, i) => at((total * i) / n));
const [ox, oz] = at(START);
const axis = raw.map(([x, z]) => [+(x - ox).toFixed(2), +(z - oz).toFixed(2)]);

writeFileSync(out, `// Generated by scripts/ikorodu-axis.mjs from OpenStreetMap data (© OpenStreetMap contributors, ODbL). Do not edit by hand.
// General Hospital Ikorodu gate to the garage roundabout centre: OSM ways 538323260 (Beach Road), 1460813931,
// 778859468 and 1460813930 (Ayangburen Road) and 134580953 (roundabout), scaled by ${SCALE}.
// Game metres: x east, z south, listed from the hospital to the roundabout. The start line is the world origin.

export const IKORODU_AXIS: [number, number][] = [
${axis.map(p => `  [${p[0]}, ${p[1]}],`).join('\n')}
];

/** Metres along the axis from the hospital end to the start line. */
export const IKORODU_START = ${START};
`);
console.log('wrote', out, 'length', total.toFixed(1), 'points', axis.length);
