// Generate src/config/ojuelegbaAxis.ts from OpenStreetMap: the westbound carriageway of Ojuelegba Road
// from just east of the Tejuosho market to under the Western Avenue bridge, scaled down for the game.
// The game never fetches map data; re-run this only to re-derive the layout:  node scripts/osm-track.mjs
// Road data © OpenStreetMap contributors (ODbL).
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'src', 'config', 'ojuelegbaAxis.ts');

// Westbound ways in driving order. The first two are drawn eastwards in OSM and get reversed.
const WAYS = [1157078040, 1489667624, 535027935, 583270859, 218590473, 585187764, 585187765];
const REVERSED = new Set([1157078040, 1489667624]);
// The Street View spot the user picked (outside the Tejuosho market), the origin of the track.
const ORIGIN = { lat: 6.508808, lon: 3.369399 };
const EAST_OF_START = 112; // real metres of road kept east of the start, for the grid and the U-turn
const WEST_OF_START = 825; // real metres from the start to under the Western Avenue bridge
const SCALE = 0.38;
const STEP = 20; // game metres between axis vertices

async function fetchWays() {
  const query = `[out:json];way(id:${WAYS.join(',')});out geom;`;
  for (let attempt = 0; attempt < 2; attempt++) {
    const res = await fetch('https://overpass-api.de/api/interpreter', {
      method: 'POST',
      headers: { 'User-Agent': 'lagos-racer/0.1', Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'data=' + encodeURIComponent(query),
    });
    const text = await res.text();
    try { return JSON.parse(text).elements; } catch { if (attempt) throw new Error('Overpass did not return JSON: ' + text.slice(0, 200)); }
    await new Promise(r => setTimeout(r, 3000));
  }
}

const R = 6371000, k = Math.cos((ORIGIN.lat * Math.PI) / 180);
/** Local metres: x east, z south. */
const local = p => [((p.lon - ORIGIN.lon) * Math.PI) / 180 * R * k, -((p.lat - ORIGIN.lat) * Math.PI) / 180 * R];

const elements = await fetchWays();
const byId = new Map(elements.map(e => [e.id, e]));
let line = [];
for (const id of WAYS) {
  const e = byId.get(id);
  if (!e) throw new Error(`way ${id} missing from the Overpass reply`);
  const pts = e.geometry.map(local);
  if (REVERSED.has(id)) pts.reverse();
  for (const p of pts) { const q = line[line.length - 1]; if (!q || Math.hypot(p[0] - q[0], p[1] - q[1]) > 0.5) line.push(p); }
}

// Distance along the line, and where the start (nearest point to the origin) sits on it.
const cum = line.map((_, i) => 0);
for (let i = 1; i < line.length; i++) cum[i] = cum[i - 1] + Math.hypot(line[i][0] - line[i - 1][0], line[i][1] - line[i - 1][1]);
let startD = 0, best = Infinity;
for (let i = 1; i < line.length; i++) {
  const [ax, az] = line[i - 1], [bx, bz] = line[i], len = cum[i] - cum[i - 1];
  const t = Math.max(0, Math.min(1, (-ax * (bx - ax) - az * (bz - az)) / (len * len)));
  const d = Math.hypot(ax + (bx - ax) * t, az + (bz - az) * t);
  if (d < best) { best = d; startD = cum[i - 1] + t * len; }
}
const at = d => {
  // Beyond the ends, carry on along the end segment.
  if (d <= 0) { const [a, b] = [line[0], line[1]], L = cum[1]; return [a[0] + (a[0] - b[0]) * (-d / L), a[1] + (a[1] - b[1]) * (-d / L)]; }
  for (let i = 1; i < line.length; i++) if (d <= cum[i]) { const t = (d - cum[i - 1]) / (cum[i] - cum[i - 1]); return [line[i - 1][0] + (line[i][0] - line[i - 1][0]) * t, line[i - 1][1] + (line[i][1] - line[i - 1][1]) * t]; }
  const n = line.length, [a, b] = [line[n - 1], line[n - 2]], L = cum[n - 1] - cum[n - 2], e = d - cum[n - 1];
  return [a[0] + (a[0] - b[0]) * (e / L), a[1] + (a[1] - b[1]) * (e / L)];
};

const from = startD - EAST_OF_START, to = startD + WEST_OF_START, realLen = to - from;
const n = Math.round((realLen * SCALE) / STEP);
const axis = [];
for (let i = 0; i <= n; i++) {
  const [x, z] = at(from + (realLen * i) / n);
  axis.push([+(x * SCALE).toFixed(2), +(z * SCALE).toFixed(2)]);
}
const start = +(EAST_OF_START * SCALE).toFixed(2);

writeFileSync(out, `// Generated by scripts/osm-track.mjs from OpenStreetMap data (© OpenStreetMap contributors, ODbL). Do not edit by hand.
// Ojuelegba Road, westbound carriageway, from ${EAST_OF_START} m east of the Tejuosho market start to under the
// Western Avenue bridge, scaled by ${SCALE}. Game metres: x east, z south, listed east to west.

export const OJUELEGBA_AXIS: [number, number][] = [
${axis.map(p => `  [${p[0]}, ${p[1]}],`).join('\n')}
];

/** Metres along the axis from its east end to the start line. */
export const OJUELEGBA_START = ${start};
`);
console.log(`axis: ${axis.length} points, length ≈ ${(realLen * SCALE).toFixed(0)} m, start ${start} m (start ${best.toFixed(1)} m from the Street View spot)`);
