// Generate src/models/generated/showroom.js from the sporty showroom (reference/sporty).
// The showroom files are classic scripts that share one global scope, so they are concatenated
// into a single ES module (minus the showroom's renderer and lights) and their builders exported.
// Re-run after changing any showroom model:  node scripts/sync-models.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'reference', 'sporty');
const outDir = path.join(root, 'src', 'models', 'generated');
const out = path.join(outDir, 'showroom.js');

const core = readFileSync(path.join(src, 'core.js'), 'utf8');
const start = core.indexOf('/* ---------- materials ---------- */');
if (start < 0) throw new Error('core.js: materials section not found');
let body = core.slice(start);

// three r128 -> current API
body = body.replace(/t\.encoding=THREE\.sRGBEncoding;/g, 't.colorSpace=THREE.SRGBColorSpace;');

let vehicles = ['okada', 'keke', 'danfo', 'brt']
  .map(v => `/* ===== vehicles/${v}.js ===== */\n` + readFileSync(path.join(src, 'vehicles', `${v}.js`), 'utf8'))
  .join('\n');

// Game build: lighter geometry than the showroom (fewer bevel, curve and round segments). Four
// vehicles are on screen at once on budget phones; the showroom keeps full detail.
const LITE = [
  ['bevelSegments:3, curveSegments:5', 'bevelSegments:1, curveSegments:3'],
  ['bevelSegments:4, curveSegments:10', 'bevelSegments:2, curveSegments:5'],
  ['function sph(r,m,x,y,z,seg=18)', 'function sph(r,m,x,y,z,seg=10)'],
  ['function cylm(rt,rb,h,m,seg=20)', 'function cylm(rt,rb,h,m,seg=10)'],
  ['function rod(a,b,r,m,seg=10)', 'function rod(a,b,r,m,seg=5)'],
  ['head.add(sph(.2,skin,0,0,0,28));', 'head.add(sph(.2,skin,0,0,0,14));'],
  ['const pts=[]; const seg=6;', 'const pts=[]; const seg=3;'],
  ['return gcache[k]=new THREE.LatheGeometry(pts,14);', 'return gcache[k]=new THREE.LatheGeometry(pts,8);'],
  ['new THREE.LatheGeometry(pts,32),MAT.tire', 'new THREE.LatheGeometry(pts,16),MAT.tire'],
  ['new THREE.LatheGeometry(pts,36),MAT.tire', 'new THREE.LatheGeometry(pts,16),MAT.tire'],
  ['new THREE.TorusGeometry(ri*.95,ri*.055,8,32)', 'new THREE.TorusGeometry(ri*.95,ri*.055,4,16)'],
  ['new THREE.CylinderGeometry(r,r,w,28,1,true,ts,tl)', 'new THREE.CylinderGeometry(r,r,w,14,1,true,ts,tl)'],
];
for (const [from, to] of LITE) {
  const n = (body.split(from).length - 1) + (vehicles.split(from).length - 1);
  if (!n) console.warn('lite: pattern not found:', from);
  body = body.split(from).join(to);
  vehicles = vehicles.split(from).join(to);
}

const exportsList = [
  'buildOkada', 'buildKeke', 'buildDanfo', 'buildBRT', 'person', 'fixedChild',
  'mat', 'paint', 'glow', 'MAT', 'mcache', 'ctex', 'textTex', 'plateTex', 'raceNumberTex', 'speedTex', 'checkerTex',
  'ANKARA', 'ANKARA2', 'PLAID', 'GELE', 'rustTex',
  'V', 'V2', 'mesh', 'rbox', 'rbGeo', 'sph', 'cylm', 'rod', 'limb', 'fender', 'decal', 'FACE',
  'rrectShape', 'profileGeo', 'capsuleGeo', 'smoothNormals', 'sportWheel', 'carWheel', 'spokedWheel',
];

const code = `// GENERATED by scripts/sync-models.mjs from reference/sporty. Do not edit by hand:
// change the showroom files and re-run the script.
/* eslint-disable */
// @ts-nocheck
import * as THREE from 'three';

${body}
${vehicles}

export { ${exportsList.join(', ')} };
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(out, code);
execFileSync(process.execPath, ['--check', out], { stdio: 'inherit' });
console.log(`wrote ${path.relative(root, out)} (${(code.length / 1024).toFixed(1)} KB)`);
